import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Seeder } from 'nestjs-seeder';
import { Guest } from './entities/guest.entity';

@Injectable()
export class GuestSeeder implements Seeder {
  constructor(
    @InjectModel(Guest.name)
    private readonly guestModel: Model<Guest>,
  ) {}

  async seed(): Promise<any> {
    const guests = [
      { firstname: 'Maman', lastname: 'DIOMANDE' },
      { firstname: 'Nadia', lastname: 'DIOMANDE' },
      { firstname: 'Amara', lastname: 'DIOMANDE' },
      { firstname: 'Ramatou', lastname: 'DIOMANDE' },
      { firstname: 'Alice', lastname: 'DIOMANDE' },
      { firstname: 'Eudes', lastname: 'DIOMANDE' },
      { firstname: 'Papa', lastname: 'COLIBRI' },
      { firstname: 'Tonton', lastname: 'Raphaël NZI' },
      { firstname: 'Tantie', lastname: "Maï N'Zi" },
      { firstname: 'Papa', lastname: 'BONGBA' },
      { firstname: 'Maman', lastname: 'BONGBA' },
      { firstname: 'Emmanuel', lastname: 'BONGBA' },
      { firstname: 'Walker & Epouse', lastname: 'BONGBA' },
      { firstname: 'Tonton', lastname: 'NICOLAS' },
      { firstname: 'Mr et Mme', lastname: 'Blanc' },
      { firstname: 'Couple', lastname: "N'GOU" },
      { firstname: 'Couple', lastname: 'ATTE' },
      { firstname: 'Couple', lastname: 'GERARD' },
      { firstname: 'Couple', lastname: 'KOFFI' },
      { firstname: 'Papa & Maman', lastname: 'JOYCE' },
      { firstname: 'Ariko', lastname: 'Marcelle' },
      { firstname: 'Tanon', lastname: 'VIVIANE' },
      { firstname: 'Nadège', lastname: null },
      { firstname: 'Prisca', lastname: null },
      { firstname: 'Gnamon', lastname: 'MELANIE' },
      { firstname: 'Mr et madame', lastname: 'Gnamon' },
      { firstname: 'Tantie', lastname: 'LEA' },
      { firstname: 'Couple', lastname: 'APOUTRI' },
      { firstname: 'Marius Hermann', lastname: 'KOUDAFOKE' },
      { firstname: 'Nadege', lastname: 'Kouame' },
      { firstname: 'Père Eluh / THIERRY', lastname: 'ROLAND / KONE' },
      { firstname: 'Père Etienne', lastname: 'K' },
      { firstname: 'Pasteur', lastname: 'KOUASSI' },
      { firstname: 'Maman', lastname: 'Pasteur' },
      { firstname: 'Franck', lastname: 'GRAGBO' },
      { firstname: 'Jean Martial', lastname: 'KOUAKOU' },
      { firstname: 'Prince', lastname: 'DON' },
      { firstname: 'Jordan', lastname: 'GRAGBO' },
      { firstname: 'Papa', lastname: 'GRAGBO' },
      { firstname: 'Ilyas', lastname: 'Georges' },
      { firstname: 'Kouassi', lastname: 'Sandra' },
      { firstname: 'Serge', lastname: 'EKRA' },
      { firstname: 'Papa', lastname: 'PASCAL' },
      { firstname: 'Maman', lastname: 'PASCAL' },
      { firstname: 'Papa', lastname: 'ANCIEN' },
      { firstname: 'Maman', lastname: 'ANCIEN' },
      { firstname: 'Monsieur & Madame', lastname: 'BENDE' },
      { firstname: 'M/Mme', lastname: 'AHUA' },
      { firstname: 'Couple', lastname: 'KOUAKOU' },
      { firstname: 'Couple', lastname: 'BEDA' },
      { firstname: 'Couple', lastname: 'DJOMO' },
      { firstname: 'Couple', lastname: 'VOUA' },
      { firstname: 'Couple', lastname: 'KADJO' },
      { firstname: 'Couple', lastname: 'OKA' },
      { firstname: 'Couple', lastname: 'AHUE' },
      { firstname: 'Couple', lastname: 'KOUASSI' },
      { firstname: 'Couple', lastname: 'KOUASSI BERNARD' },
      { firstname: 'Salvana', lastname: 'LEU' },
      { firstname: 'Nadège', lastname: 'AHUA' },
      { firstname: 'Moni', lastname: 'MARC' },
      { firstname: 'Maman', lastname: 'KATIE' },
      { firstname: 'Madame', lastname: 'GBATA' },
      { firstname: 'Filles de Maman', lastname: null },
      { firstname: 'Oriane', lastname: 'CANFRIN' },
      { firstname: 'Korédé', lastname: 'ODJO-BELLA' },
      { firstname: 'Rasak', lastname: 'ALLI' },
      { firstname: 'Cynthia', lastname: 'KOIDIO' },
      { firstname: 'Mame', lastname: 'SALL' },
      { firstname: 'Paul', lastname: 'NOBI' },
      { firstname: 'Melissa', lastname: 'YIBA' },
      { firstname: 'Abass', lastname: 'BAMBA' },
      { firstname: 'Wilfried', lastname: 'ASSOUAN' },
      { firstname: 'Jean Tolla', lastname: 'KONAN' },
      { firstname: 'Franck', lastname: 'ELLEINGAND' },
      { firstname: 'Paul-Harry', lastname: 'AITHNARD' },
      { firstname: 'Léticia', lastname: "N'CHO TRAORE" },
      { firstname: 'Kahi', lastname: 'LUMUMBA + Team Totem' },
      { firstname: 'Wilfried', lastname: 'AMOIKON' },
      { firstname: 'Arsène', lastname: 'LOUH' },
      { firstname: 'Joseph', lastname: 'OYETOLA' },
      { firstname: 'Karen', lastname: 'KOUAKOU' },
      { firstname: 'Maureen', lastname: 'YAO' },
      { firstname: 'Ibrahim', lastname: 'TOGOLA (+ 2 Digits)' },
      { firstname: 'Adolphe', lastname: 'GOULEHI' },
      { firstname: 'Moussa', lastname: 'TOURE' },
      { firstname: 'Yannick', lastname: 'ABILY' },
      { firstname: 'Philipe', lastname: 'DARGA' },
      { firstname: 'Herbert', lastname: 'KOFFI' },
      { firstname: 'Hermann', lastname: 'TANOH' },
      { firstname: 'Yolande', lastname: 'KOUAME' },
      { firstname: 'Ange', lastname: 'ATSE' },
      { firstname: 'Zakarie', lastname: 'KONE' },
      { firstname: 'Hamed', lastname: 'KONE' },
      { firstname: 'Amanda', lastname: 'ZOHOURI' },
      { firstname: 'Sabou', lastname: 'COULIBALY' },
      { firstname: 'Souhalio', lastname: 'BAMBA' },
      { firstname: 'Mory', lastname: 'KONE' },
      { firstname: 'Brahima', lastname: 'TRAORE' },
      { firstname: 'Francine', lastname: 'AFFELI' },
      { firstname: 'Amenan', lastname: 'YAO' },
      { firstname: 'Melissandre', lastname: 'ASSEMIAN' },
      { firstname: 'Abdoulaye', lastname: 'ZANGO' },
      { firstname: 'Yannick', lastname: 'KABRAN' },
      { firstname: 'Morel', lastname: 'KOUAKOU' },
      { firstname: 'Hugues', lastname: 'ROMEO' },
      { firstname: 'Christ Donald', lastname: 'DJAMAN' },
      { firstname: 'Trévor', lastname: 'KONAN' },
      { firstname: 'Audrey', lastname: 'GBA' },
      { firstname: 'Reine', lastname: 'HONAPOLY' },
      { firstname: 'Madame', lastname: 'ASSALE' },
      { firstname: 'Fatou', lastname: 'VEGUESS' },
      { firstname: 'Tiorna', lastname: 'COULIBALY' },
      { firstname: 'Moreau', lastname: 'TREICH' },
      { firstname: 'Fatim', lastname: 'FOFANA' },
      { firstname: 'Awa', lastname: 'SIRANI' },
      { firstname: 'Aminata', lastname: 'DIALLO' },
      { firstname: 'Aziz', lastname: 'FOFANA' },
      { firstname: 'Lassiné', lastname: 'C.' },
      { firstname: 'Yannick', lastname: 'DALLI' },
      { firstname: 'Chorale/Famille', lastname: 'ADC - STEJ' },
      { firstname: 'Mégane', lastname: 'GOHOU' },
      { firstname: 'Mohamed', lastname: 'KONE' },
      { firstname: 'Ami', lastname: 'SANOGO' },
      { firstname: 'Adja', lastname: 'MASSAO' },
      { firstname: 'Basile', lastname: 'GAMENE' },
      { firstname: 'Reine', lastname: 'Kadja' },
      { firstname: 'Sarah', lastname: null },
      { firstname: 'Madame', lastname: 'GBATA' },
      { firstname: 'Wilfried', lastname: 'Marcory' },
      { firstname: 'Maman', lastname: 'WILFRIED' },
      { firstname: 'Fabio', lastname: null },
      { firstname: 'Mr et mme', lastname: 'Tiemoko' },
      { firstname: 'Loes', lastname: 'YAO' },
      { firstname: 'Pierre', lastname: "M'BRA" },
      { firstname: 'Wilfried', lastname: 'KOFFI' },
      { firstname: 'Pascal', lastname: 'YAO' },
      { firstname: 'El Hadj Daouda', lastname: 'OUATTARA' },
      { firstname: 'Alex', lastname: 'MIEZAN' },
      { firstname: 'Lorraine Willy', lastname: 'DADIE' },
      { firstname: 'Sandrine', lastname: 'L.' },
      { firstname: 'Doria Rodolphe', lastname: 'MANGUET' },
      { firstname: 'Olga', lastname: 'L.' },
      { firstname: 'Vanessa', lastname: 'ZOUZOU' },
      { firstname: 'Awa', lastname: 'MARTHE' },
      { firstname: 'Marie Mathilde', lastname: 'Kouassi' },
      { firstname: 'Marina', lastname: 'KOUAME' },
      { firstname: 'Richmond', lastname: 'COFFI' },
      { firstname: 'Souleymane', lastname: 'COULIBALY' },
      { firstname: 'Christian', lastname: 'BONI' },
      { firstname: 'Famille', lastname: 'Daddy' },
      { firstname: 'Jerachmel', lastname: 'KOH' },
      { firstname: 'Brigitte', lastname: 'OUEGNIN' },
    ];

    // Insert into the database.
    return this.guestModel.insertMany(guests);
  }

  async drop(): Promise<any> {
    return this.guestModel.deleteMany({});
  }
}
